import Head from 'next/head'
import Layout from '../components/Layout'
import profilePic from '../../public/images/profile/Steph2bg.png'
import Image from 'next/image'
import AnimatedText from '../components/AnimatedText'
import Link from 'next/link'
import HireMe from '@/components/HireMe'
import { motion, useMotionValue, useTransform } from 'framer-motion'
import { useState } from 'react'
import color from '../../public/images/icons/color-picker.png'
import eraser from '../../public/images/icons/eraser.png'




export default function Home() {

  const [isClicked, setClicked] = useState(false)
  const [imageSrc, setImageSrc] = useState();
  const colors = ["#CCF5AC", "#F9F5E3", "#EF798A", "#D14081", '#7E2E84'] 
  // ['#F2F6D0', '#D0E1D4', '#D9D2B6', '#E4BE9E', '#71697A']
  const bgColor = ['#f5f5f5']
  
  const x = useMotionValue(200)
  const y = useMotionValue(200)

  const rotateX = useTransform(y, [0, 400], [15, -15])
  const rotateY = useTransform(x, [0, 400], [-10, 10])

    function handleMouse(event) {
        x.set(event.pageX)
        y.set(event.pageY)
    }


  return (
    <>
      <Head>
        <title>Stephanie's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <motion.main className='flex items-center text-dark w-full lgmin-h-screen dark:!text-light dark:!bg-dark'
       animate={{ backgroundColor: isClicked ? colors : bgColor }}
       transition={{ 
        repeat: Infinity,
        repeatType: "mirror",
        ease: "easeInOut",
        duration: 4, 
      }}
       >
    
    <div className='flex flex-col gap-12 ml-2 top-[110px] absolute '>
        
        <motion.div className='flex flex-col text-center text-[9px] items-center justify-center w-[1.5rem] h-[1.5rem] lg:w-[2.5rem] lg:h-[2.5rem] dark:hidden text-dark cursor-grab'
            drag
            dragElastic={1}
            dragConstraints={{ top: 0, right: 0, bottom: 0, left: 0 }}
            onDragEnd={() => setClicked(true)}
            whileHover={{ cursor: "grabbing" }}
            >
            <Image src={color} alt='color picker' className='pointer-events-none cursor-none ' />
            Drag Me</motion.div>
      </div>

      <div className='flex flex-col gap-12 ml-2 top-[190px] absolute '>

          <motion.div className='flex flex-col text-center items-center text-[9px] justify-center w-[1.5rem] h-[1.5rem] lg:w-[2.5rem] lg:h-[2.5rem] dark:hidden text-dark cursor-pointer shadow-sm'
            drag
            dragElastic={1}
            dragConstraints={{ top: 0, right: 0, bottom: 0, left: 0 }}
            onDragEnd={() => setClicked(false)}
            whileHover={{ cursor: "grabbing" }}
            >
            <Image src={eraser} alt='magic eraser' className='pointer-events-none cursor-none'/>
            Drag To Reset
        </motion.div>
      </div>
        

         

        
       <Layout className='p-10 lg:p-20 m-10 md:m-25 lg:m-36 relative'>
      
        <motion.div className="flex items-center justify-between h-80 w-full cursor-none  dark:!text-light dark:!bg-dark"
         animate={{ backgroundColor: isClicked ? colors : bgColor }}
         transition={{ 
          repeat: Infinity,
          repeatType: "mirror",
          ease: "easeInOut",
          duration: 4, 
        }}
        onMouseMove={handleMouse}
        >
          <motion.div className='w-1/2 flex items-center justify-center relative cursor-grab'
           style={{
            rotateX: rotateX,
            rotateY: rotateY,
        }}
          >
        
            <Image src={profilePic} alt='developer' className='w-[38rem] h-[28rem] md:w-[45rem] md:h-[40rem] lg:w-full lg:h-[45rem] pointer-events-none cursor-none pt-8 md:pt-16 lg:pt-8 ' />
          </motion.div>
          

          <div className='w-1/2 flex flex-col items-center self-center'>
            
            <AnimatedText text={`Hi, I'm Stephanie. A Front End Web Designer`} className='!text-2xl md:text-3xl xl:!text-5xl !text-left mt-6'/>
            <p className='my-4 mx-2 lg:my-4 text-xs md:text-md lg:text-lg font-medium'>
            As a designer I strive to strongly focus on building solutions that users actually want, and to create beautiful, functional UI's.
            </p>
            <div className='flex items-center self-start'>
              <Link href='/StephanieDavisResume.pdf' target={'_blank'} className='flex items-center mb-8 lg:mb-10 bg-dark text-light p-1.5 lg:p-2 px-6 rounded-lg text-xs lg:text-lg font-semibold hover:bg-light hover:text-dark border-solid border-transparent hover:border-dark border-2 dark:hover:bg-dark dark:hover:text-light dark:hover:border-light dark:bg-light dark:text-dark'
              download={true}
              >Resume 
              
              </Link>
              <Link href='mailto:stephmdavis1@gmail.com' target={'_blank'} className='ml-4 text-xs lg:text-lg mb-8 lg:mb-10 font-medium capitalize text-dark underline dark:text-light dark:underline'>Contact Me</Link>
            </div>
          </div>
        </motion.div>
        

 
       </Layout>

       <HireMe  />
      
      </motion.main>
      </>
  )
}
